version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: it-essega
    container_name: it-essega
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - '8000:8000'
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/z-local.ini
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.1
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: apa_je_nanti
      MYSQL_DATABASE: it-essega
      MYSQL_USER: apa_je_nanti
      MYSQL_PASSWORD: apa_je_nanti
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - laravel

  litespeed:
    image: litespeedtech/openlitespeed:latest
    container_name: litespeed
    restart: unless-stopped
    ports:
      - '80:80'
      - '8088:8088'
      - '7080:7080'
    volumes:
      - ./:/var/www
    depends_on:
      - app
    networks:
      - laravel

volumes:
  mysql-data:

networks:
  laravel:
    driver: bridge
